### ISSUE TITLE
deprecation warning

### ISSUE THREAD

**Issue by alexanderadam** [Thulium-Drake/ansible-role-docker_services#1]
Nothing serious. I just wanted to say, that

```yml
  docker_swarm:
    state: 'inspect'
```
is deprecated (`[DEPRECATION WARNING]: The 'inspect' state is deprecated, please use 'docker_swarm_info' to inspect swarm cluster. This feature will be removed in version 2.12.`).
Thank you _so much_ for this repo :pray:

**Comment by Thulium-Drake** [comment]
Oh wow... I missed this XD

But good news, I fixed it in august last year ;-) with bbd730a8e68f15d456192dd131c8660a341ac41b
